version: "3"
services:
  ansible:
    build:
      context: .
      dockerfile: dockerfiles/ansible.dockerfile
    container_name: ansible_container
    networks:
      - ansible_network
    volumes:
      - ./.ssh:/root/.ssh
      - ./ansible_playbooks:/ansible_playbooks
      - ./executables:/executables
    working_dir: /ansible_playbooks
    depends_on:
      - ubuntu1
      - ubuntu2
      - ubuntu3
    tty: true
    stdin_open: true

  ubuntu1:
    build:
      context: .
      dockerfile: dockerfiles/ubuntu.dockerfile
    container_name: ubuntu1
    networks:
      - ansible_network
    ports:
      - "8081:80"
    volumes:
      - ./nginx-config/default.conf:/etc/nginx/sites-enabled/default:ro
      - ./src:/var/www/html
    tty: true
    stdin_open: true

  ubuntu2:
    build:
      context: .
      dockerfile: dockerfiles/ubuntu.dockerfile
    container_name: ubuntu2
    networks:
      - ansible_network
    ports:
      - "8082:80"
    volumes:
      - ./nginx-config/default.conf:/etc/nginx/sites-enabled/default:ro
      - ./src:/var/www/html
    tty: true
    stdin_open: true

  ubuntu3:
    build:
      context: .
      dockerfile: dockerfiles/ubuntu.dockerfile
    container_name: ubuntu3
    networks:
      - ansible_network
    ports:
      - "8083:80"
    volumes:
      - ./nginx-config/default.conf:/etc/nginx/sites-enabled/default:ro
      - ./src:/var/www/html
    tty: true
    stdin_open: true

  nginx-lb:
    image: nginx:latest
    container_name: nginx_lb
    networks:
      - ansible_network
    ports:
      - "8080:80"
    volumes:
      - ./nginx-config/nginx-lb.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ubuntu1
      - ubuntu2
      - ubuntu3

networks:
  ansible_network:
    driver: bridge
