- name: Configure Ubuntu Servers
  hosts: ubuntu_servers
  become: yes
  tasks:
    - name: Copy NGINX install script to servers
      copy:
        src: /executables/install-nginx.sh
        dest: /tmp/install-nginx.sh
        mode: "0755"

    - name: Execute the install-nginx.sh script
      command: sh /tmp/install-nginx.sh
